auto: true

markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title.html
#paginate: 8
permalink: /:title

name: “Sunorg”
title: Sunorg
description: Summit Plan
url: http://sunorg.net
feed: /atom.xml
author_info: <a href="http://sunorg.net/“>Sunorg</a>
